blank_issues_enabled: false
contact_links:
  - name: Patreon
    url: https://www.patreon.com/evanyou
    about: Love Vue.js? Please consider supporting us via Patreon.
  - name: Open Collective
    url: https://opencollective.com/vuejs/donate
    about: Love Vue.js? Please consider supporting us via Open Collective.
